import React from 'react'

const Cookiepolicy = () => {
  return (
    <div>
        <p>
        This is the Cookie policy of The Hotel (hereafter “The Hotel”, “we” or “our”). The Hotel is a public limited company under Belgian law, whose registered office is established at Boulevard de Waterloo 38, 1000 Brussels and which is known in the crossroads bank of enterprises under number BE 0889.633.520 (Belgium).

This Cookie policy aims at informing you about the use of cookies by The Hotel. This policy should be read together with The Hotel’s Privacy Statement.

The Cookie policy can be modified, e.g. as a result of new functionalities on the website that require the processing of personal data. Any major changes will be announced on our website.

This version of the Cookie policy was last modified on 25/09/2018.

CONTENT

THE HOTEL WEBSITE AND COOKIES
WHAT ARE COOKIES?
WHICH COOKIES DO WE USE?
HOW CAN YOU DELETE COOKIES?
QUESTIONS?
1 THE HOTEL WEBSITE AND COOKIES

When you visit our website, we collect certain information by automated means, using cookies. We may also use other technologies such as pixel tags, browser analysis tools, server logs, and web beacons for similar purposes as described in this policy and we may include them on our website, in marketing e-mail messages or our newsletter, affiliated websites, etc., to determine whether messages have been opened and links have been clicked on. The information provided below about cookies also applies to these other technologies.

2 WHAT ARE COOKIES?

Cookies are small text files that are installed on your browser, on your computer or on your mobile device. They allow a website to recognize your device. Cookies can have several purposes: to ensure that the website takes into account the user’s preferences by for example remembering language preferences, passwords and log-in details, to collect statistical data, to adapt the content, etc.

3 WHICH COOKIES DO WE USE?

Below you will find a summary of the cookies that The Hotel uses on its website:

Essential cookies

These cookies allow our website to work optimally and in a secure way. These cookies enable core site functionality and are automatically enabled when you use our website.

Name

Purpose

 Retention Period

Domain

_cfduid

Used to identify individual clients behind a shared IP address and apply security settings on a per-client basis https://support.cloudflare.com/hc/en-us/articles/200170156-What-does-the-CloudFlare-cfduid-cookie-do-

5 years

Cloudfare

Cookieconsent_status

Used to register your cookie consent through the cookie banner

As long as your browser history isn’t deleted

The Hotel

 

Analytics cookies

Analytical cookies allow us to analyze the use of our website. These cookies measure information, such as the number of visits, the pages that were visited and the frequency of your visit. They give us insight into the performance of our website. For this purpose, we mainly use third-party cookies from Google Analytics. When you first visit our website, we will inform you about this and request your consent.

The information generated by Google Analytics cookies about your use of our website - standard information about access to the internet (including your IP address) and your anonymously analyzed user behavior - is transmitted to Google, which stores them on servers that may be installed in the United States. Google adheres to the principles of the EU-US privacy shield (Privacy Shield). [Before storing the transmitted information, Google will make it anonymous by deleting the last octet of your IP address.]

The Google Analytics privacy policy states that Google uses this information to evaluate the use you make of the website and to generate, for The Hotel, reports on the activity of the website. For more information about using Google Analytics, please review Google's Privacy Policy and in particular how Google uses certain data collected when you use partner sites or apps. You can disable Google Analytics by using the Browser Add-on for disabling Google Analytics. For more information about using Hotjar, please review Hotjar’s Privacy Policy. You can disable Hotjar’s cookies by using the do not track header. 

Name

Purpose

Retention period

Domain

_ga

Google Analytics – used to distinguish users

2 years

Google

_gat

Google Analytics -  used to throttle request rate

1 minute

Google

_gid

Google Analytics -  used to distinguish users

1 day

Google

_hjClosedSurveyInvites

Used to ensure that the same invite does not re-appear if it has already been shown.

365 days

Hotjar

_hjDonePolls

Used to ensure that the same poll does not re-appear if it has already been filled in.

365 days

Hotjar

_hjMinimizedPolls

Used to ensure that the widget stays minimizes when the visitor navigates through your site.

365 days

Hotjar

_hjDoneTestersWidgets

Used to ensure that the same form does not re-appear if it has already been filled in.

365 days

Hotjar

_hjMinimizedTestersWidgets

Used to ensure that the widget stays minimizes when the visitor navigates through your site.

365 days

Hotjar

_hjIncludedInSample

Set to let Hotjar know whether that visitor is included in the sample which is used to generate funnels

365 days

Hotjar

_hjShownFeedbackMessage

Set when a visitor minimizes or completes Incoming Feedback. 

365 days

Hotjar

_hjid

Used to persist the random user ID, unique to that site on the browser. 

365 days

Hotjar

 

Advertising cookies

These cookies collect information about the user's browsing habits in order to make advertising more relevant to the user and his interests.

We use these cookies to show other content that is relevant to the user’s interest and to measure the effectiveness of online marketing campaigns.

Name

Purpose

Retention period

Domain

1P_JAR

Used for user tracking and ad targeting purposes

1 week

Google

NID

Used for user tracking and ad targeting purposes

6 months

Google

 

Third parties such as Google provide these cookies. This Cookie Policy does not apply to the use of your information by third parties. Therefore, The Hotel advises you to check the cookie policies of these third parties.

4 HOW CAN YOU DELETE COOKIES?

Your internet browser allows you to prevent the use of cookies, to receive a warning when a cookie is installed or to later delete the cookies from your hard disk. By way of example, the below hyperlinks provide more guidance on how to disable the use of cookies on certain browsers and/or on how to delete cookies.

Chrome: https://support.google.com/chrome/answer/95647?hl=en
Internet Explorer: http://windows.microsoft.com/en-US/windows-vista/Block-or-allow-cookies
Mozilla Firefox: https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences?redirectlocale=en-US&redirectslug=Enabling+and+disabling+cookies and https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored
Safari: https://support.apple.com/en-gb/HT201265
For more general information on deleting or blocking cookies, please visit: http://www.allaboutcookies.org/Opens in a new tab.

5 QUESTIONS?

If you have further questions or complaints about this website or about this Cookie Policy, you can contact us:

By e-mail at info@thehotel.be
By mail:
The Hotel Brussels
Boulevard de Waterloo 38
1000 Brussels
        </p>
    </div>
  )
}

export default Cookiepolicy